=== AdhamEltantawy/bcit-courses/Archives/COMP 4711 - Internet Software Development/F6/web/WEB-INF/data/team_roster.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- The Football Team -->
<!ELEMENT team (player)*>
<!ATTLIST team
    name CDATA #IMPLIED
  >
<!--- A player within the team -->
<!ELEMENT player (birthdate|position|name)*>
<!ATTLIST player
    jersey CDATA #IMPLIED
  >

<!--- A player's name -->
<!ELEMENT name (#PCDATA)>

<!--- A player's position on the team -->
<!ELEMENT position (#PCDATA)>

<!--- A player's birthdate -->
<!ELEMENT birthdate (#PCDATA)>

=== AdhamEltantawy/bcit-courses/Internet/F6/web/WEB-INF/data/AC_Horsens_roster.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE team SYSTEM "team_roster.dtd">

<!--
    Document   : AC_Horsens.xml
    Created on : April 1, 2009, 12:59 AM
    Author     : Steffen L. Norgren
    Description: Team roster for AC Horsens
        Purpose of the document follows.
-->

<team name="AC Horsens">
    <player jersey="1">
        <name>Søren Jochumsen</name>
        <position>Goalkeeper</position>
        <birthdate>1976-08-01</birthdate>
    </player>
    <player jersey="21">
        <name>Lasse Sørensen</name>
        <position>Goalkeeper</position>
        <birthdate>1982-03-06</birthdate>
    </player>
    <player jersey="30">
        <name>Allan Nielsen</name>
        <position>Goalkeeper</position>
        <birthdate>1987-07-28</birthdate>
    </player>
    <player jersey="2">
        <name>Kenneth Emil Petersen</name>
        <position>Forward</position>
        <birthdate>1985-01-15</birthdate>
    </player>
    <player jersey="3">
        <name>Morten 'Molle' Rasmussen</name>
        <position>Forward</position>
        <birthdate>1985-03-26</birthdate>
    </player>
    <player jersey="4">
        <name>Mads Rieper</name>
        <position>Forward</position>
        <birthdate>1973-07-20</birthdate>
    </player>
    <player jersey="5">
        <name>Adam Eckersley</name>
        <position>Forward</position>
        <birthdate>1985-09-07</birthdate>
    </player>
    <player jersey="22">
        <name>Andreas Augustsson</name>
        <position>Forward</position>
        <birthdate>1976-11-26</birthdate>
    </player>
    <player jersey="24">
        <name>Nabil Aslam</name>
        <position>Forward</position>
        <birthdate>1984-08-03</birthdate>
    </player>
    <player jersey="26">
        <name>Marc Maze</name>
        <position>Forward</position>
        <birthdate>1988-10-17</birthdate>
    </player>
    <player jersey="6">
        <name>Simon Nagel</name>
        <position>Midfielder</position>
        <birthdate>1985-07-05</birthdate>
    </player>
    <player jersey="8">
        <name>Martin Spelmann</name>
        <position>Midfielder</position>
        <birthdate>1987-03-21</birthdate>
    </player>
    <player jersey="10">
        <name>Allan Søgaard</name>
        <position>Midfielder</position>
        <birthdate>1978-01-20</birthdate>
    </player>
    <player jersey="11">
        <name>Niels Lodberg</name>
        <position>Midfielder</position>
        <birthdate>1980-10-14</birthdate>
    </player>
    <player jersey="13">
        <name>Thomas Kortegaard</name>
        <position>Midfielder</position>
        <birthdate>1984-07-02</birthdate>
    </player>
    <player jersey="14">
        <name>Søren Friis</name>
        <position>Midfielder</position>
        <birthdate>1976-12-13</birthdate>
    </player>
    <player jersey="20">
        <name>Janus Drachmann</name>
        <position>Midfielder</position>
        <birthdate>1988-05-11</birthdate>
    </player>
    <player jersey="23">
        <name>Steffen Lauser</name>
        <position>Midfielder</position>
        <birthdate>1984-03-04</birthdate>
    </player>
    <player jersey="25">
        <name>Yasin Avci</name>
        <position>Midfielder</position>
        <birthdate>1984-08-03</birthdate>
    </player>
    <player jersey="27">
        <name>Anders Nøhr</name>
        <position>Midfielder</position>
        <birthdate>1981-09-03</birthdate>
    </player>
    <player jersey="9">
        <name>Gilberto Macena</name>
        <position>Defender</position>
        <birthdate>1984-04-01</birthdate>
    </player>
    <player jersey="12">
        <name>Rawez Lawan</name>
        <position>Defender</position>
        <birthdate>1987-10-04</birthdate>
    </player>
    <player jersey="16">
        <name>Besart Berisha</name>
        <position>Defender</position>
        <birthdate>1985-07-29</birthdate>
    </player>
    <player jersey="17">
        <name>Casper Johansen</name>
        <position>Defender</position>
        <birthdate>1988-07-28</birthdate>
    </player>
    <player jersey="19">
        <name>Nick Christensen</name>
        <position>Defender</position>
        <birthdate>1985-08-28</birthdate>
    </player>
    <player jersey="29">
        <name>Jimmy Mayasi</name>
        <position>Defender</position>
        <birthdate>1987-06-06</birthdate>
    </player>
</team>

=== AdhamEltantawy/bcit-courses/Internet/F6/web/WEB-INF/data/Odense_BK_roster.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE team SYSTEM "team_roster.dtd">

<!--
    Document   : Odense_BK.xml
    Created on : April 1, 2009, 12:59 AM
    Author     : Steffen L. Norgren
    Description: Team roster for Odense BK
        Purpose of the document follows.
-->

<team name="Odense BK">
    <player jersey="1">
        <name>Arkadiusz Onyszko</name>
        <position>Goalkeeper</position>
        <birthdate>1974-01-12</birthdate>
    </player>
    <player jersey="16">
        <name>David Preece</name>
        <position>Goalkeeper</position>
        <birthdate>1976-08-26</birthdate>
    </player>
    <player jersey="35">
        <name>Christian Kier</name>
        <position>Goalkeeper</position>
        <birthdate>1988-05-17</birthdate>
    </player>
    <player jersey="2">
        <name>Espen Ruud</name>
        <position>Forward</position>
        <birthdate>1984-02-28</birthdate>
    </player>
    <player jersey="3">
        <name>Atle Roar Håland</name>
        <position>Forward</position>
        <birthdate>1977-07-26</birthdate>
    </player>
    <player jersey="5">
        <name>Anders Møller Christensen</name>
        <position>Forward</position>
        <birthdate>1977-07-26</birthdate>
    </player>
    <player jersey="6">
        <name>Thomas Helveg</name>
        <position>Forward</position>
        <birthdate>1971-06-24</birthdate>
    </player>
    <player jersey="15">
        <name>Chris Sørensen</name>
        <position>Forward</position>
        <birthdate>1977-07-27</birthdate>
    </player>
    <player jersey="18">
        <name>Jonas Troest</name>
        <position>Forward</position>
        <birthdate>1985-03-04</birthdate>
    </player>
    <player jersey="20">
        <name>Timmi Johansen</name>
        <position>Forward</position>
        <birthdate>1987-05-08</birthdate>
    </player>
    <player jersey="4">
        <name>Hans Henrik Andreasen</name>
        <position>Midfielder</position>
        <birthdate>1979-01-10</birthdate>
    </player>
    <player jersey="8">
        <name>Henrik Hansen</name>
        <position>Midfielder</position>
        <birthdate>1979-07-28</birthdate>
    </player>
    <player jersey="14">
        <name>Esben Hansen</name>
        <position>Midfielder</position>
        <birthdate>1981-08-10</birthdate>
    </player>
    <player jersey="17">
        <name>Morten Bisgaard</name>
        <position>Midfielder</position>
        <birthdate>1974-06-25</birthdate>
    </player>
    <player jersey="19">
        <name>Eric Djemba-Djemba</name>
        <position>Midfielder</position>
        <birthdate>1981-05-04</birthdate>
    </player>
    <player jersey="21">
        <name>Peter Nymann</name>
        <position>Midfielder</position>
        <birthdate>1982-08-22</birthdate>
    </player>
    <player jersey="23">
        <name>Anders Nielsen</name>
        <position>Midfielder</position>
        <birthdate>1989-05-29</birthdate>
    </player>
    <player jersey="7">
        <name>Peter Utaka</name>
        <position>Defender</position>
        <birthdate>1984-02-12</birthdate>
    </player>
    <player jersey="10">
        <name>Björn Runström</name>
        <position>Defender</position>
        <birthdate>1984-03-01</birthdate>
    </player>
    <player jersey="11">
        <name>Johan Absalonsen</name>
        <position>Defender</position>
        <birthdate>1985-09-16</birthdate>
    </player>
    <player jersey="22">
        <name>Njogu Demba-Nyrén</name>
        <position>Defender</position>
        <birthdate>1979-06-26</birthdate>
    </player>
    <player jersey="28">
        <name>Anders K. Jacobsen</name>
        <position>Defender</position>
        <birthdate>1989-10-27</birthdate>
    </player>
</team>
