=== AdhamEltantawy/bcit-courses/Internet/lab3/web/Courses.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT courses (course)*>
<!ELEMENT course (holeDetails|scratchScore|contactNumber|postalCode|country|sate_prov|city|address|name)*>
<!ATTLIST course courseID CDATA #IMPLIED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT sate_prov (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT postalCode (#PCDATA)>
<!ELEMENT contactNumber (#PCDATA)>
<!ELEMENT scratchScore (#PCDATA)>
<!ELEMENT holeDetails (hole)*>
<!ELEMENT hole (info|yards|par)*>
<!ATTLIST hole holeNum CDATA #IMPLIED>
<!ELEMENT par (#PCDATA)>
<!ELEMENT yards (#PCDATA)>
<!ELEMENT info (#PCDATA)>

=== AdhamEltantawy/bcit-courses/Internet/lab3/web/Courses.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Courses.xml
    Created on : February 1, 2009, 10:17 PM
    Author     : Steffen L. Norgren
    Description:
        Contains golf course information.
-->

<!DOCTYPE courses SYSTEM "Courses.dtd">

<courses>
    <course courseID="1">
        <name>Gleneagles Golf &amp; Country Club</name>
        <address>2721 Seymore Way.</address>
        <city>North Vancouver</city>
        <sate_prov>BC</sate_prov>
        <country>Canada</country>
        <postalCode>V7R 2X8</postalCode>
        <contactNumber>604-929-0111</contactNumber>
        <scratchScore>50</scratchScore>
        <holeDetails>
            <hole holeNum="1">
                <par>4</par>
                <yards>285</yards>
                <info>Looks pretty</info>
            </hole>
            <hole holeNum="2">
                <par>5</par>
                <yards>380</yards>
                <info>Lots of squirrels</info>
            </hole>
            <hole holeNum="3">
                <par>4</par>
                <yards>310</yards>
                <info>Cliffside</info>
            </hole>
            <hole holeNum="4">
                <par>3</par>
                <yards>170</yards>
                <info>Water features</info>
            </hole>
            <hole holeNum="5">
                <par>3</par>
                <yards>210</yards>
                <info>Nothing special</info>
            </hole>
            <hole holeNum="6">
                <par>4</par>
                <yards>235</yards>
                <info>Dancing unicorns</info>
            </hole>
            <hole holeNum="7">
                <par>5</par>
                <yards>450</yards>
                <info>Nuclear waste site</info>
            </hole>
            <hole holeNum="8">
                <par>3</par>
                <yards>220</yards>
                <info>View of abattoir</info>
            </hole>
            <hole holeNum="9">
                <par>5</par>
                <yards>375</yards>
                <info>Fresh beef</info>
            </hole>
        </holeDetails>
    </course>
    <course courseID="2">
        <name>Hollyburn Golf &amp; Country Club</name>
        <address>3734 Dollarton Hwy.</address>
        <city>North Vancouver</city>
        <sate_prov>BC</sate_prov>
        <country>Canada</country>
        <postalCode>V7R E5E</postalCode>
        <contactNumber>604-929-1847</contactNumber>
        <scratchScore>50</scratchScore>
        <holeDetails>
            <hole holeNum="1">
                <par>4</par>
                <yards>285</yards>
                <info>Looks pretty</info>
            </hole>
            <hole holeNum="2">
                <par>5</par>
                <yards>380</yards>
                <info>Lots of squirrels</info>
            </hole>
            <hole holeNum="3">
                <par>4</par>
                <yards>310</yards>
                <info>Cliffside</info>
            </hole>
            <hole holeNum="4">
                <par>3</par>
                <yards>170</yards>
                <info>Water features</info>
            </hole>
            <hole holeNum="5">
                <par>3</par>
                <yards>210</yards>
                <info>Nothing special</info>
            </hole>
            <hole holeNum="6">
                <par>4</par>
                <yards>235</yards>
                <info>Dancing unicorns</info>
            </hole>
            <hole holeNum="7">
                <par>5</par>
                <yards>450</yards>
                <info>Nuclear waste site</info>
            </hole>
            <hole holeNum="8">
                <par>3</par>
                <yards>220</yards>
                <info>View of abattoir</info>
            </hole>
            <hole holeNum="9">
                <par>5</par>
                <yards>375</yards>
                <info>Fresh beef</info>
            </hole>
        </holeDetails>
    </course>
    <course courseID="3">
        <name>Semiahmoo &amp; Country Club</name>
        <address>21238 16th Ave.</address>
        <city>Surrey</city>
        <sate_prov>BC</sate_prov>
        <country>Canada</country>
        <postalCode>V4B 5R2</postalCode>
        <contactNumber>604-535-7874</contactNumber>
        <scratchScore>50</scratchScore>
        <holeDetails>
            <hole holeNum="1">
                <par>4</par>
                <yards>285</yards>
                <info>Looks pretty</info>
            </hole>
            <hole holeNum="2">
                <par>5</par>
                <yards>380</yards>
                <info>Lots of squirrels</info>
            </hole>
            <hole holeNum="3">
                <par>4</par>
                <yards>310</yards>
                <info>Cliffside</info>
            </hole>
            <hole holeNum="4">
                <par>3</par>
                <yards>170</yards>
                <info>Water features</info>
            </hole>
            <hole holeNum="5">
                <par>3</par>
                <yards>210</yards>
                <info>Nothing special</info>
            </hole>
            <hole holeNum="6">
                <par>4</par>
                <yards>235</yards>
                <info>Dancing unicorns</info>
            </hole>
            <hole holeNum="7">
                <par>5</par>
                <yards>450</yards>
                <info>Nuclear waste site</info>
            </hole>
            <hole holeNum="8">
                <par>3</par>
                <yards>220</yards>
                <info>View of abattoir</info>
            </hole>
            <hole holeNum="9">
                <par>5</par>
                <yards>375</yards>
                <info>Fresh beef</info>
            </hole>
        </holeDetails>
    </course>
</courses>
