=== AdhamEltantawy/bcit-courses/Internet/lab3/build/web/Players.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT players (player)*>
<!ELEMENT player (handicaps|playerRounds|contactNumber|postalCode|country|sate_prov|city|address|lastName|firstName)*>
<!ATTLIST player playerID CDATA #IMPLIED >
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT sate_prov (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT postalCode (#PCDATA)>
<!ELEMENT contactNumber (#PCDATA)>
<!ELEMENT playerRounds (golfRound)*>
<!ELEMENT golfRound (holes|weatherCondition|holesPlayed|endDateTime|startDateTime)*>
<!ATTLIST golfRound courseID CDATA #IMPLIED roundID CDATA #IMPLIED>
<!ELEMENT startDateTime (#PCDATA)>
<!ELEMENT endDateTime (#PCDATA)>
<!ELEMENT holesPlayed (#PCDATA)>
<!ELEMENT weatherCondition (#PCDATA)>
<!ELEMENT holes (hole)*>
<!ELEMENT hole (score)*>
<!ATTLIST hole holeNum CDATA #IMPLIED >
<!ELEMENT score (#PCDATA)>
<!ELEMENT handicaps (handicap)*>
<!ELEMENT handicap (score|date)*>
<!ELEMENT date (#PCDATA)>

=== AdhamEltantawy/bcit-courses/Internet/lab3/web/Players.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Players.xml
    Created on : February 1, 2009, 10:17 PM
    Author     : Steffen L. Norgren
    Description:
        Contains player information.
-->

<!DOCTYPE players SYSTEM "Players.dtd">

<players>
    <player playerID="1">
        <firstName>Steffen</firstName>
        <lastName>Norgren</lastName>
        <address>13872 Malabar Ave.</address>
        <city>White Rock</city>
        <sate_prov>BC</sate_prov>
        <country>Canada</country>
        <postalCode>V4B 2X9</postalCode>
        <contactNumber>778-889-4498</contactNumber>
        <playerRounds>
            <golfRound roundID="1" courseID="1">
                <startDateTime>2008-12-01 12:42:32</startDateTime>
                <endDateTime>2008-12-01 15:32:11</endDateTime>
                <holesPlayed>9</holesPlayed>
                <weatherCondition>Sunny</weatherCondition>
                <holes>
                    <hole holeNum="1">
                        <score>4</score>
                    </hole>
                    <hole holeNum="2">
                        <score>2</score>
                    </hole>
                    <hole holeNum="3">
                        <score>5</score>
                    </hole>
                    <hole holeNum="4">
                        <score>2</score>
                    </hole>
                    <hole holeNum="5">
                        <score>3</score>
                    </hole>
                    <hole holeNum="6">
                        <score>7</score>
                    </hole>
                    <hole holeNum="7">
                        <score>3</score>
                    </hole>
                    <hole holeNum="8">
                        <score>2</score>
                    </hole>
                    <hole holeNum="9">
                        <score>6</score>
                    </hole>
                </holes>
            </golfRound>
            <golfRound roundID="2" courseID="2">
                <startDateTime>2008-12-12 08:47:01</startDateTime>
                <endDateTime>2008-12-12 10:01:57</endDateTime>
                <holesPlayed>9</holesPlayed>
                <weatherCondition>Freezing Rain</weatherCondition>
                <holes>
                    <hole holeNum="1">
                        <score>8</score>
                    </hole>
                    <hole holeNum="2">
                        <score>9</score>
                    </hole>
                    <hole holeNum="3">
                        <score>7</score>
                    </hole>
                    <hole holeNum="4">
                        <score>10</score>
                    </hole>
                    <hole holeNum="5">
                        <score>12</score>
                    </hole>
                    <hole holeNum="6">
                        <score>18</score>
                    </hole>
                    <hole holeNum="7">
                        <score>9</score>
                    </hole>
                    <hole holeNum="8">
                        <score>6</score>
                    </hole>
                    <hole holeNum="9">
                        <score>9</score>
                    </hole>
                </holes>
            </golfRound>
            <golfRound roundID="3" courseID="3">
                <startDateTime>2009-01-14 17:42:32</startDateTime>
                <endDateTime>2009-01-14 19:32:11</endDateTime>
                <holesPlayed>9</holesPlayed>
                <weatherCondition>Clowdy and Wind Gusts</weatherCondition>
                <holes>
                    <hole holeNum="1">
                        <score>6</score>
                    </hole>
                    <hole holeNum="2">
                        <score>5</score>
                    </hole>
                    <hole holeNum="3">
                        <score>6</score>
                    </hole>
                    <hole holeNum="4">
                        <score>4</score>
                    </hole>
                    <hole holeNum="5">
                        <score>3</score>
                    </hole>
                    <hole holeNum="6">
                        <score>3</score>
                    </hole>
                    <hole holeNum="7">
                        <score>4</score>
                    </hole>
                    <hole holeNum="8">
                        <score>4</score>
                    </hole>
                    <hole holeNum="9">
                        <score>3</score>
                    </hole>
                </holes>
            </golfRound>
        </playerRounds>
        <handicaps>
            <handicap>
                <date>2008-12-01</date>
                <score>34</score>
            </handicap>
            <handicap>
                <date>2008-12-12</date>
                <score>88</score>
            </handicap>
            <handicap>
                <date>2009-01-14</date>
                <score>35</score>
            </handicap>
        </handicaps>
    </player>
    <player playerID="2">
        <firstName>Stuart</firstName>
        <lastName>Porter</lastName>
        <address>663 Riverside Dr</address>
        <city>North Vancouver</city>
        <sate_prov>BC</sate_prov>
        <country>Canada</country>
        <postalCode>V7R 4M7</postalCode>
        <contactNumber>604-929-0686</contactNumber>
        <playerRounds>
            <golfRound roundID="4" courseID="1">
                <startDateTime>2008-12-01 12:42:32</startDateTime>
                <endDateTime>2008-12-01 15:32:11</endDateTime>
                <holesPlayed>9</holesPlayed>
                <weatherCondition>Sunny</weatherCondition>
                <holes>
                    <hole holeNum="1">
                        <score>4</score>
                    </hole>
                    <hole holeNum="2">
                        <score>2</score>
                    </hole>
                    <hole holeNum="3">
                        <score>5</score>
                    </hole>
                    <hole holeNum="4">
                        <score>2</score>
                    </hole>
                    <hole holeNum="5">
                        <score>3</score>
                    </hole>
                    <hole holeNum="6">
                        <score>7</score>
                    </hole>
                    <hole holeNum="7">
                        <score>3</score>
                    </hole>
                    <hole holeNum="8">
                        <score>2</score>
                    </hole>
                    <hole holeNum="9">
                        <score>6</score>
                    </hole>
                </holes>
            </golfRound>
            <golfRound roundID="5" courseID="2">
                <startDateTime>2008-12-12 08:47:01</startDateTime>
                <endDateTime>2008-12-12 10:01:57</endDateTime>
                <holesPlayed>9</holesPlayed>
                <weatherCondition>Freezing Rain</weatherCondition>
                <holes>
                    <hole holeNum="1">
                        <score>8</score>
                    </hole>
                    <hole holeNum="2">
                        <score>9</score>
                    </hole>
                    <hole holeNum="3">
                        <score>7</score>
                    </hole>
                    <hole holeNum="4">
                        <score>10</score>
                    </hole>
                    <hole holeNum="5">
                        <score>12</score>
                    </hole>
                    <hole holeNum="6">
                        <score>18</score>
                    </hole>
                    <hole holeNum="7">
                        <score>9</score>
                    </hole>
                    <hole holeNum="8">
                        <score>6</score>
                    </hole>
                    <hole holeNum="9">
                        <score>9</score>
                    </hole>
                </holes>
            </golfRound>
            <golfRound roundID="6" courseID="3">
                <startDateTime>2009-01-14 17:42:32</startDateTime>
                <endDateTime>2009-01-14 19:32:11</endDateTime>
                <holesPlayed>9</holesPlayed>
                <weatherCondition>Clowdy and Wind Gusts</weatherCondition>
                <holes>
                    <hole holeNum="1">
                        <score>6</score>
                    </hole>
                    <hole holeNum="2">
                        <score>5</score>
                    </hole>
                    <hole holeNum="3">
                        <score>6</score>
                    </hole>
                    <hole holeNum="4">
                        <score>4</score>
                    </hole>
                    <hole holeNum="5">
                        <score>3</score>
                    </hole>
                    <hole holeNum="6">
                        <score>3</score>
                    </hole>
                    <hole holeNum="7">
                        <score>4</score>
                    </hole>
                    <hole holeNum="8">
                        <score>4</score>
                    </hole>
                    <hole holeNum="9">
                        <score>3</score>
                    </hole>
                </holes>
            </golfRound>
        </playerRounds>
        <handicaps>
            <handicap>
                <date>2008-12-01</date>
                <score>34</score>
            </handicap>
            <handicap>
                <date>2008-12-12</date>
                <score>88</score>
            </handicap>
            <handicap>
                <date>2009-01-14</date>
                <score>35</score>
            </handicap>
        </handicaps>
    </player>
    <player playerID="3">
        <firstName>Maureen</firstName>
