=== AdhamEltantawy/bcit-courses/Internet/F6/web/WEB-INF/data/team_schedule.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- The root schedule -->
<!ELEMENT schedule (game)*>
<!ATTLIST schedule
    team CDATA #IMPLIED
  >

<!--- A game between two teams. -->
<!ELEMENT game (away|score|home|status)*>
<!ATTLIST game
    date CDATA #IMPLIED
  >

<!--- The game's current status. -->
<!ELEMENT status (#PCDATA)>

<!--- The home team. -->
<!ELEMENT home (#PCDATA)>

<!--- The final score. -->
<!ELEMENT score (#PCDATA)>

<!--- The away team. -->
<!ELEMENT away (#PCDATA)>

=== AdhamEltantawy/bcit-courses/Internet/F6/web/WEB-INF/data/AC_Horsens_schedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schedule SYSTEM "team_schedule.dtd">

<!--
    Document   : AC_Horsens_schedule.xml
    Created on : April 1, 2009, 2:31 AM
    Author     : Steffen L. Norgren
    Description:
        Purpose of the document follows.
-->

<schedule team="AC Horsens">
    <game date="2008-07-20">
        <status>Final</status>
        <home>AC Horsens</home>
        <score>2 - 0</score>
        <away>Sonderjyske</away>
    </game>
    <game date="2008-07-28">
        <status>Final</status>
        <home>AGF Aarhus</home>
        <score>3 - 1</score>
        <away>AC Horsens</away>
    </game>
    <game date="2008-08-03">
        <status>Final</status>
        <home>FC Midtjylland</home>
        <score>2 - 1</score>
        <away>AC Horsens</away>
    </game>
    <game date="2008-08-09">
        <status>Final</status>
        <home>AC Horsens</home>
        <score>0 - 1</score>
        <away>Brøndby</away>
    </game>
    <game date="2008-08-17">
        <status>Final</status>
        <home>AC Horsens</home>
        <score>0 - 0</score>
        <away>Vejle</away>
    </game>
    <game date="2008-08-31">
        <status>Final</status>
        <home>Esbjerg</home>
        <score>0 - 1</score>
        <away>AC Horsens</away>
    </game>
    <game date="2008-09-14">
        <status>Final</status>
        <home>AC Horsens</home>
        <score>1 - 1</score>
        <away>Randers FC</away>
    </game>
    <game date="2008-09-20">
        <status>Final</status>
        <home>AC Horsens</home>
        <score>1 - 2</score>
        <away>Odense BK</away>
    </game>
    <game date="2008-10-04">
        <status>Final</status>
        <home>AaB</home>
        <score>1 - 1</score>
        <away>AC Horsens</away>
    </game>
    <game date="2008-10-18">
        <status>Final</status>
        <home>AC Horsens</home>
        <score>0 - 1</score>
        <away>FC Copenhagen</away>
    </game>
    <game date="2008-10-26">
        <status>Final</status>
        <home>FC Nordsjælland</home>
        <score>3 - 1</score>
        <away>AC Horsens</away>
    </game>
    <game date="2008-11-03">
        <status>Final</status>
        <home>Brøndby</home>
        <score>4 - 3</score>
        <away>AC Horsens</away>
    </game>
    <game date="2008-11-09">
        <status>Final</status>
        <home>AC Horsens</home>
        <score>1 - 1</score>
        <away>AGF Aarhus</away>
    </game>
    <game date="2008-11-16">
        <status>Final</status>
        <home>AC Horsens</home>
        <score>2 - 2</score>
        <away>Randers FC</away>
    </game>
    <game date="2008-11-23">
        <status>Final</status>
        <home>Esbjerg</home>
        <score>1 - 0</score>
        <away>AC Horsens</away>
    </game>
    <game date="2008-11-30">
        <status>Final</status>
        <home>AC Horsens</home>
        <score>0 - 3</score>
        <away>Sonderjyske</away>
    </game>
    <game date="2008-12-07">
        <status>Final</status>
        <home>FC Copenhagen</home>
        <score>5 - 2</score>
        <away>AC Horsens</away>
    </game>
    <game date="2009-03-01">
        <status>Final</status>
        <home>AC Horsens</home>
        <score>0 - 1</score>
        <away>AaB</away>
    </game>
    <game date="2009-03-08">
        <status>Final</status>
        <home>AC Horsens</home>
        <score>2 - 1</score>
        <away>Odense BK</away>
    </game>
    <game date="2009-03-15">
        <status>Final</status>
        <home>FC Nordsjælland</home>
        <score>1 - 2</score>
        <away>AC Horsens</away>
    </game>
    <game date="2009-03-22">
        <status>Final</status>
        <home>AC Horsens</home>
        <score>0 - 0</score>
        <away>Vejle</away>
    </game>
    <game date="2009-04-05">
        <status>10:05 ET</status>
        <home>FC Midtjylland</home>
        <score>N/A</score>
        <away>AC Horsens</away>
    </game>
    <game date="2009-04-09">
        <status>10:05 ET</status>
        <home>AGF Aarhus</home>
        <score>N/A</score>
        <away>AC Horsens</away>
    </game>
    <game date="2009-04-12">
        <status>11:30 ET</status>
        <home>AC Horsens</home>
        <score>N/A</score>
        <away>Brøndby</away>
    </game>
    <game date="2009-04-19">
        <status>10:00 ET</status>
        <home>AC Horsens</home>
        <score>N/A</score>
        <away>Esbjerg</away>
    </game>
    <game date="2009-04-22">
        <status>12:00 ET</status>
        <home>Randers FC</home>
        <score>N/A</score>
        <away>AC Horsens</away>
    </game>
    <game date="2009-04-25">
        <status>11:00 ET</status>
        <home>AC Horsens</home>
        <score>N/A</score>
        <away>FC Copenhagen</away>
    </game>
    <game date="2009-05-03">
        <status>10:00 ET</status>
        <home>Sonderjyske</home>
        <score>N/A</score>
        <away>AC Horsens</away>
    </game>
    <game date="2009-05-10">
        <status>9:00 ET</status>
        <home>AC Horsens</home>
        <score>N/A</score>
        <away>FC Midtjylland</away>
    </game>
    <game date="2009-05-13">
        <status>13:00 ET</status>
        <home>Vejle</home>
        <score>N/A</score>
        <away>AC Horsens</away>
    </game>
    <game date="2009-05-17">
        <status>9:00 ET</status>
        <home>AaB</home>
        <score>N/A</score>
        <away>AC Horsens</away>
    </game>
    <game date="2009-05-24">
        <status>9:00 ET</status>
        <home>AC Horsens</home>
        <score>N/A</score>
        <away>FC Nordsjælland</away>
    </game>
    <game date="2009-05-31">
        <status>9:00 ET</status>
        <home>Odense BK</home>
        <score>N/A</score>
        <away>AC Horsens</away>
    </game>
</schedule>
